// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtWCWfRx4UaM08y59hSQ1MXfnZ5URiMos',
    appId: '1:1074247383706:web:2d2b20e42380c253d1fd23',
    messagingSenderId: '1074247383706',
    projectId: 'lost-and-found-73e7a',
    authDomain: 'lost-and-found-73e7a.firebaseapp.com',
    storageBucket: 'lost-and-found-73e7a.firebasestorage.app',
    measurementId: 'G-8NVD7XG7DW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgkHxaAnTTzjWuoWeWx3Lm2mPGgMChl2M',
    appId: '1:1074247383706:android:c3266f2890a1fe4cd1fd23',
    messagingSenderId: '1074247383706',
    projectId: 'lost-and-found-73e7a',
    storageBucket: 'lost-and-found-73e7a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAojLbQr1txTTmMRttBIEy6P1dPcs42EIc',
    appId: '1:1074247383706:ios:829be46923ec01d6d1fd23',
    messagingSenderId: '1074247383706',
    projectId: 'lost-and-found-73e7a',
    storageBucket: 'lost-and-found-73e7a.firebasestorage.app',
    iosBundleId: 'com.example.lostFound',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAojLbQr1txTTmMRttBIEy6P1dPcs42EIc',
    appId: '1:1074247383706:ios:829be46923ec01d6d1fd23',
    messagingSenderId: '1074247383706',
    projectId: 'lost-and-found-73e7a',
    storageBucket: 'lost-and-found-73e7a.firebasestorage.app',
    iosBundleId: 'com.example.lostFound',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtWCWfRx4UaM08y59hSQ1MXfnZ5URiMos',
    appId: '1:1074247383706:web:2e324729c9925935d1fd23',
    messagingSenderId: '1074247383706',
    projectId: 'lost-and-found-73e7a',
    authDomain: 'lost-and-found-73e7a.firebaseapp.com',
    storageBucket: 'lost-and-found-73e7a.firebasestorage.app',
    measurementId: 'G-YM549VQDC6',
  );
}
